version: '2.3'

services:
  postgres:
    container_name: diaspora_postgres
    image: postgres:9.6-alpine
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=diaspora
      - POSTGRES_PASSWORD=diaspora
      - POSTGRES_DB=diaspora_production

  redis:
    container_name: diaspora_redis
    image: redis:4.0-alpine
    restart: always
    volumes:
      - ./redis:/data

  unicorn:
    container_name: diaspora_unicorn
    image: dsterry/diaspora
    command: unicorn
    restart: always
    volumes:
      - ./data:/diaspora/public/
    depends_on:
      - postgres
      - redis
    environment:
      - DB_TYPE=postgresql
      - DB_HOST=postgres
      - DB_USER=diaspora
      - DB_PASSWORD=diaspora

  sidekiq:
    container_name: diaspora_sidekiq
    image: dsterry/diaspora
    restart: always
    command: sidekiq
    volumes:
      - ./data:/diaspora/public/
    depends_on:
      - postgres
      - redis
    environment:
      - DB_TYPE=postgresql
      - DB_HOST=postgres
      - DB_USER=diaspora
      - DB_PASSWORD=diaspora

  nginx:
    container_name: diaspora_nginx
    image: nginx:stable
    restart: always
    volumes:
      - ./nginx-vhost.conf:/etc/nginx/conf.d/default.conf:ro
      - ./data:/var/www/html
    ports:
      - 127.0.0.1:80:80
